<?php

declare(strict_types=1);

namespace Ziumper\MultiClassMap;

class AutoloadSpliter {
    
    private string $classmapFile;
    private string $staticFile;
    
    public function __construct(private string $vendorDir) {
        $this->classmapFile = $this->vendorDir . '/composer/autoload_classmap.php';
        $this->staticFile = $this->vendorDir . '/composer/autoload_static.php';
    }
    
    public function getClassMapParts(): array 
    {
        return $this->getParts($this->classmapFile);
    }
    
    /**
     * 
     * We are taking the path without vendor to redo 
     * a install map, it may change how composer auto-load is doing 
     * things in future, this way we just do our thing 
     * 
     * @param string $file
     * @return array
     */
    private function getParts(string $file) {
        if (!file_exists($file)) {
            return [];
        }

        $classmap = include $file;

        $parts = [];
        
        foreach ($classmap as $class => $path) {
            $pathWithoutVendor = str_replace($this->vendorDir, '', $path);
            
            //gets the first prefix of the class name after first '\' sign
            $prefix = explode('\\', $class, 2)[0] ?: 'global';
            $parts[$prefix][$class] = $pathWithoutVendor;
        }
            
        return $parts;
    }
    
    
    public function getStaticParts(): array 
    {
        return $this->getParts($this->staticFile);
    }
    
    
    //TODO Composer\Autoload\AutoLoadGenerator - reuse it for my own generation of auto load class map files
    public function split(): void
    {
        $parts = $this->getClassMapParts();        
        $generatedPartName = [];

        //save the specifc files into seperated class map files
        foreach ($parts as $name => $map) {
            $partContent = <<< PHP
            <?php 
            // autoload_classmap_{$name}.php part @generated by MultiClassMapPlugin (aggregates per-prefix parts)

            \$vendorDir = dirname(dirname(__FILE__));
            \$baseDir = dirname(\$vendorDir);
                    
            return array(
            
            PHP;
            
            foreach($map as $className => $path) {
                $classNameWithDoubleBackwardSlash = str_replace("\\","\\\\",$className);
                $partContent .= <<<PHP
                    "$classNameWithDoubleBackwardSlash" => \$vendorDir . "$path",
                        
                PHP;
            }
            
       
            //end the file partial adds closing and new line
            $partContent .= ");\n";
            $fileName = $this->vendorDir . "/composer/autoload_classmap_{$name}.php";
            $generatedPartName[] = $name;
            file_put_contents(
                filename: $fileName,
                data: $partContent
            );
        }
        
        sort($generatedPartName);

        //prepare autoload splitted 
        $autoloadContent = <<<PHP
        <?php
        // autoload_classmap.php @generated by MultiClassMapPlugin (aggregates per-prefix parts)

        \$vendorDir = dirname(dirname(__FILE__));
        \$baseDir = dirname(\$vendorDir);

        \$map = [];

        \$parts = array(

        PHP;
        
        foreach($generatedPartName as $fileName) {
            $autoloadContent .= <<<PHP
            \$vendorDir . '/composer/autoload_classmap_$fileName.php',
                  
            PHP;
        }
        
        $autoloadContent .= ");\n\n";
        
        $autoloadContent .= <<<PHP
        foreach (\$parts as \$file) {
            // include each partial array
            \$part = include \$file;
            if (is_array(\$part)) {
                \$map += \$part;
            }
        }

        return \$map;
        PHP; 
        
        unlink($this->classmapFile);
        
        file_put_contents(
            filename: $this->classmapFile, 
            data: $autoloadContent
        );
    }
}
